[package]
name = "test-suites"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-fixed-point-math = { workspace = true }
vault = { path = "../vault", features = ["testutils"] }
trading = { path = "../trading", features = ["testutils"] }
sep-40-oracle = { workspace = true, features = ["testutils"] }
sep-41-token = { workspace = true, features = ["testutils"] }